apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maven-run-
spec:
  pipelineRef:
    name: maven-build
  params:
    - name: git-repo
      value: https://github.com/jkhelil/sample-maven.git
    - name: git-revision
      value: main
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
    - name: maven-settings
      emptyDir: {}
    - name: maven-local-m2
      emptyDir: {}
